### ISSUE TITLE
Doesn't work with images in content

### ISSUE THREAD

**Issue by colourmafia** [storypioneers/kirby-wysiwyg#44]
I cannot drag the files from the file list into the content like you can with the default editor. If I instead just insert the image syntax (image: photo1.jpg) then all formatting disappears from the final rendered text and I just get a huge block of text (all html elements are stripped).

Anyone else having this problem and know of a fix?

**Comment by chrisvasey** [comment]
I am not sure if this plugin is being maintained anymore as my last pull request has not been looked at and no issues have been addressed for months but I am also facing the same issue.
Looking to try and add the functionality to add images within WYSIWYG as I now have customers asking for this.

Shall update this issue after I have done this and create another pull request though not sure if it will be merged.

Maybe someone else can provide a fix for this but till then good luck :)

**Comment by chrisvasey** [comment]
If this is crucial to you maybe take a look at [this plugin](http://getkirby-plugins.com/visual-markdown-editor) - might be able to fulfil the same function as what you need

**Comment by colourmafia** [comment]
Thanks @chrisvasey - I just tried that plugin but still getting the same issue. Then I tried the default editor and realised the issue remains with that - so not sure what's going on, but it's at base level!

**Comment by chrisvasey** [comment]
@colourmafia are you using the HTML-Minify plugin?
This has been known to break the img functionality in the Kirby Panel.

**Comment by colourmafia** [comment]
Nope! No other plugins installed (and only script is jquery as I'm running bootstrap)

**Comment by dgdsp** [comment]
hi :)

unfortunately inline images are not a working feature of this plugin.

the initial maintainer, @JonasDoebertin seems to be too busy to add/fix stuff, sorry about that.

in case anyone want's to step up as maintainer, pls let me know :)

**Comment by bugsysop** [comment]
For drag and drop of image this was working for me (long time ago)
https://github.com/storypioneers/kirby-wysiwyg/issues/27#issuecomment-190743423

In your `config.pht` file:
```
c::set('field.wysiwyg.dragdrop.kirby', true);
c::set('field.wysiwyg.dragdrop.medium', true);
```
